-- Backup de mtkin.cartas gerado em 2026-03-15T17:24:49.789Z
-- Total de registros: 84

INSERT INTO mtkin.cartas (id, nome_carta, tipo_carta, caminho_imagem, categoria, equipar_onde, n_pode_equipar, forca, item, nivel, fulga_minima, texto_da_carta, permite_mochila, qtd_max, valor, uso_em_combate) VALUES
(1, 'Tô de folga', 'Cidade', 'Cartas/Cidade/1.png', 'Chacaras', '80', NULL, 1, 0, 0, 0, 'Poucos momentos para relaxar, mas quando dá essa rede e piscina são a fonte de renovação, força +1.', FALSE, 1, 0, FALSE),
(2, 'Gancho', 'Cidade', 'Cartas/Cidade/10.jpg', 'Isca', NULL, NULL, 0, 0, 0, 0, 'Consegue roubar a carta de item de um jogador, escolha uma carta na mochila ou cartela dele, use em qualquer combate.', TRUE, 2, 0, FALSE),
(3, 'Pó espanta zumbi', 'Cidade', 'Cartas/Cidade/11.jpg', 'Isca', NULL, NULL, 0, 0, 0, 0, 'Pó que ao jogar afasta zumbi devido a confundir o cheiro de humanos, use para trocar o zumbi por outro da sua mão para combater.', TRUE, 2, 0, FALSE),
(4, 'Fraco', 'Cidade', 'Cartas/Cidade/12.jpg', 'Isca', NULL, NULL, 0, 0, 0, 0, 'Espirre em um zumbi q ele vai perder a força, -4 de força para o zumbi, pegue 1 item a menos.', TRUE, 2, 0, FALSE),
(5, 'Modificador', 'Cidade', 'Cartas/Cidade/13.jpg', 'Isca', '86', NULL, 0, 0, 0, 0, 'Pode modificar um item fazendo ele ficar mais forte, coloque junto de um item da carteira e este item vai te dar +3 de força.', TRUE, 2, 0, FALSE),
(6, 'Dentro do esgoto', 'Cidade', 'Cartas/Cidade/14.jpg', 'Isca', NULL, NULL, 0, 0, 0, 0, 'Passe pelo esgoto para subir um nível, cartas de chácara com 0 força sobre um nível junto.', TRUE, 1, 0, FALSE),
(7, 'Sangue contaminado', 'Cidade', 'Cartas/Cidade/15.jpg', 'Isca', NULL, NULL, 0, 0, 0, 0, 'Jogue esta carta em um zumbi para duplicar a força dele, os itens também duplicam.', TRUE, 2, 0, FALSE),
(8, 'Mochila rasgada', 'Cidade', 'Cartas/Cidade/16.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'Sua mochila possui um rasgo, perca um item sem peso.', TRUE, 2, 0, FALSE),
(9, 'Armadilha de urso', 'Cidade', 'Cartas/Cidade/17.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'Você prendeu o pé nessa armadilha, perca uma carta de pé.', FALSE, 2, 0, FALSE),
(10, 'Contrato secreto', 'Cidade', 'Cartas/Cidade/18.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'Entregue ao espião uma carta de valor, ele vai roubar as cartas dos jogadores que somadas deem o valor da sua carta, se o jogador não tiver este valor ele perde um nível.', TRUE, 1, 0, FALSE),
(11, 'Paranoia de identidade', 'Cidade', 'Cartas/Cidade/19.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'Descarte o personagem q estiver usando e troque pelo primeiro que encontrar no descarte, se não tiver um personagem apenas descarte o seu.', TRUE, 1, 0, FALSE),
(12, 'Nazaré', 'Cidade', 'Cartas/Cidade/2.png', 'Chacaras', '80', NULL, 1, 0, 0, 0, 'Lugar de oração e um abrigo com uma vista estratégica, força +1.', FALSE, 1, 0, FALSE),
(13, 'Combinado', 'Cidade', 'Cartas/Cidade/20.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'Um jogador da direita e um da esquerda de quem recebeu esta carta combinam de roubar uma carta da mochila da vitima.', TRUE, 1, 0, FALSE),
(14, 'MOCHILA RASGADA', 'Cidade', 'Cartas/Cidade/21.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'Perca um item pesado.', TRUE, 2, 0, FALSE),
(15, 'Colete falsificado', 'Cidade', 'Cartas/Cidade/22.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'Perca um item de corpo.', TRUE, 2, 0, FALSE),
(16, 'Traindo escondido', 'Cidade', 'Cartas/Cidade/23.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'O jogador que te deu esta carta estava escondido e empurrou vc para trás, perca 1 nível.', TRUE, 2, 0, FALSE),
(17, 'Mão na mochila', 'Cidade', 'Cartas/Cidade/24.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'Descarte um item da mochila.', TRUE, 3, 0, FALSE),
(18, 'Arame esticado', 'Cidade', 'Cartas/Cidade/25.jpg', 'Armadilha', NULL, NULL, 0, 0, 0, 0, 'Você não viu esse arame? perca um item de cabeça.', TRUE, 2, 0, FALSE),
(19, 'Lerdo', 'Cidade', 'Cartas/Cidade/26.jpg', 'Zumbie', NULL, NULL, 1, 1, 1, 0, 'Devagar mais te pega, se perder o combate perde o que estiver usando na cabeça e um item aleatório da mochila, se não tiver nada na cabeça perca 1 nível.', FALSE, 1, 0, FALSE),
(20, 'Rapido', 'Cidade', 'Cartas/Cidade/27.jpg', 'Zumbie', NULL, NULL, 5, 2, 1, 0, 'Corre, esse é rápido, necessário +2 para fuga, se perder descarte toda sua mão ou perde 2 níveis.', FALSE, 1, 0, FALSE),
(21, 'Lerdo', 'Cidade', 'Cartas/Cidade/28.jpg', 'Zumbie', NULL, NULL, 3, 1, 1, 0, 'se derrotar usando a carta fraco ganhe um item adicional, +2 contra personagem de força 2, se perder perde um item da mochila e um item da cartela, a sua escolha.', FALSE, 1, 0, FALSE),
(22, 'Mutação', 'Cidade', 'Cartas/Cidade/29.jpg', 'Zumbie', NULL, NULL, 18, 5, 2, 0, 'Não persegue jogadores que estão abaixo do nível 4, se perder perde tudo que tem na mochila e na mão.', FALSE, 1, 0, FALSE),
(23, 'Moondust', 'Cidade', 'Cartas/Cidade/3.png', 'Chacaras', '80', NULL, 0, 0, 1, 4, 'Já não tínhamos muito, e este vírus tirou o resto que sobrou, fuga >=4.', FALSE, 1, 0, FALSE),
(24, 'Gordo', 'Cidade', 'Cartas/Cidade/30.jpg', 'Zumbie', NULL, NULL, 10, 3, 1, 0, 'Uma dessa na cabeça e te deixa um pouco tonto, se perder perde o que esta na cabeça e 3 níveis.', FALSE, 1, 0, FALSE),
(25, 'Mestre', 'Cidade', 'Cartas/Cidade/31.jpg', 'Zumbie', NULL, NULL, 20, 5, 2, 0, 'Não persegue jogadores com nível inferior a 5, se perder para ele é melhor deixar tudo p traz, descarte toda sua mão e cartela, pode ficar com a mochila personagem e sua fazenda. ', FALSE, 1, 0, FALSE),
(26, 'Lerdo', 'Cidade', 'Cartas/Cidade/26.jpg', 'Zumbie', NULL, NULL, 1, 0, 0, 0, NULL, FALSE, 1, 0, FALSE),
(27, 'Rapido', 'Cidade', 'Cartas/Cidade/27.jpg', 'Zumbie', NULL, NULL, 5, 0, 0, 0, NULL, FALSE, 1, 0, FALSE),
(28, 'Gordo', 'Cidade', 'Cartas/Cidade/34.jpg', 'Zumbie', NULL, NULL, 8, 2, 1, 0, 'Só pode combater este zumbi com o valor do nível, se perder perde sua fazenda e 3 níveis.', FALSE, 1, 0, FALSE),
(29, 'Gordo mutado', 'Cidade', 'Cartas/Cidade/35.jpg', 'Zumbie', NULL, NULL, 12, 3, 1, 0, '+3 de força contra jogadores que possuem força na sua carta, de perder perde o que estiver usando no pé e 1 nível.', FALSE, 2, 0, FALSE),
(30, 'Explosivo', 'Cidade', 'Cartas/Cidade/36.jpg', 'Zumbie', NULL, NULL, 16, 4, 2, 0, 'Não ataca jogadores que estão antes do nível 3, jogadores que estejam depois disso voltam 2 níveis, se perder ele explode e vc perde todas as cartas da carteira e da mão.', FALSE, 2, 0, FALSE),
(31, 'Gordo mutado', 'Cidade', 'Cartas/Cidade/37.jpg', 'Zumbie', NULL, NULL, 16, 4, 2, 0, 'Não ataca jogadores que estão antes do nível 3, jogadores que estejam depois disso voltam 2 níveis mesmo se escaparem, se perder ele te corta e vc volta para o nível 1.', FALSE, 1, 0, FALSE),
(32, 'Rastejante', 'Cidade', 'Cartas/Cidade/38.jpg', 'Zumbie', NULL, NULL, 1, 1, 1, 0, 'Rastejantes tem pouca velocidade, porem ao tropeçar em um pode ter grandes problemas.', FALSE, 5, 0, FALSE),
(34, 'Bela vista', 'Cidade', 'Cartas/Cidade/4.jpg', 'Chacaras', '80', NULL, 2, 0, 0, 0, 'Nesse lugar o barulho dentro da casa não atrai zumbi, pois a cachoeira abafa os sons, força +2.', FALSE, 1, 0, FALSE),
(35, 'Henry', 'Cidade', 'Cartas/Cidade/40.jpg', 'Sobrevivente', '79', '82', 1, 0, 0, 4, 'Jovem nem terminou o colegial e já esta sozinho cuidando de sua irmã mais nova, força +1, fuga >=4, não pode usar itens de corpo. ', FALSE, 1, 0, FALSE),
(36, 'Sheyla', 'Cidade', 'Cartas/Cidade/41.jpg', 'Sobrevivente', '79', '81', 1, 0, 0, 4, 'Após perder o marido, ficou sozinha cuidando de sua fazenda, força +1, Fuga >=4, não pode usar itens de cabeça.', FALSE, 1, 0, FALSE),
(37, 'Lucas', 'Cidade', 'Cartas/Cidade/42.jpg', 'Sobrevivente', '79', '82', 1, 0, 0, 0, 'Estudante que ao perder os pais nesse caos ficou para proteger a família, força +1', FALSE, 1, 0, FALSE),
(38, 'Leila', 'Cidade', 'Cartas/Cidade/43.jpg', 'Sobrevivente', '79', '82', 0, 0, 0, 4, 'Filha unica e com a morte dos pais ficou para cuidar dos avôs, fuga >= 4', FALSE, 1, 0, FALSE),
(39, 'Leandro', 'Cidade', 'Cartas/Cidade/44.jpg', 'Sobrevivente', '79', '85', 2, 0, 0, 0, 'Antigo Xerife da região, mas nesse cenário é apenas mais um sobrevivente, força +2, não pode usar itens de pé.', FALSE, 1, 0, FALSE),
(40, 'Recanto das aguas', 'Cidade', 'Cartas/Cidade/5.jpg', 'Chacaras', '80', NULL, 1, 0, 0, 0, 'Fonte de alimento abundante na pesca, se ajudar um jogador sobre de nível junto, força +1', FALSE, 1, 0, FALSE),
(41, 'Renascer', 'Cidade', 'Cartas/Cidade/6.jpg', 'Chacaras', '80', NULL, 1, 0, 0, 0, 'Único lugar com cheiro agradável em toda a região, força +1', FALSE, 1, 0, FALSE),
(42, 'Recanto alegre', 'Cidade', 'Cartas/Cidade/7.jpg', 'Chacaras', '80', NULL, 0, 0, 0, 4, 'Não sobrou mais os gados, mas ainda temos a terra para plantio, fuga >=4.', FALSE, 1, 0, FALSE),
(43, 'Alpendre', 'Cidade', 'Cartas/Cidade/8.jpg', 'Chacaras', '80', NULL, 0, 0, 0, 4, 'Chácara responsável pela distribuição de Milho na região, <=4 fuga', FALSE, 1, 0, FALSE),
(44, 'Estalinho', 'Cidade', 'Cartas/Cidade/9.jpg', 'Isca', NULL, NULL, 0, 0, 0, 0, 'Use este item para escapar de um zumbi em um combate e ainda pegar dois itens.', TRUE, 2, 0, FALSE),
(45, 'Ajuda familiar', 'Item', 'Cartas/Itens/1.jpg', 'Descartavel', NULL, NULL, 3, 0, 0, 0, '+3 de força para qualquer um dos lados.', TRUE, 3, 100, TRUE),
(46, 'Terra no olho', 'Item', 'Cartas/Itens/10.jpg', 'Descartavel', NULL, NULL, 0, 0, 0, 0, 'Jogue no olho de um zumbi, ele não consegue te perseguir e vc foge do combate.', TRUE, 1, 200, FALSE),
(48, 'Volte a batalha', 'Item', 'Cartas/Itens/12.jpg', 'Descartavel', NULL, NULL, 0, 0, 0, 0, 'O jogador volta para o combate mesmo que ele tenha conseguido fugir.', TRUE, 1, 100, FALSE),
(49, 'Coberta', 'Item', 'Cartas/Itens/13.jpg', 'carteira', '86', NULL, 1, 0, 0, 0, 'Nas noites frias esse item te deixa mais descansado para o próximo dia, +1 de força.', TRUE, 2, 200, FALSE),
(50, 'Item fake', 'Item', 'Cartas/Itens/14.jpg', 'Descartavel', NULL, NULL, 0, 0, 0, 0, 'Deixe esta isca para um jogador do nível superior pegar, ele será obrigado a te ajudar sem pedir nada em troca, vc não sobre de nível ao vencer o combate.', TRUE, 2, 600, FALSE),
(51, 'Visão noturna', 'Item', 'Cartas/Itens/15.jpg', 'carteira', '86', NULL, 3, 0, 0, 0, 'No escuro esse óculos faz uma enorme diferença, +3 de força.', TRUE, 1, 0, FALSE),
(52, 'Pochete', 'Item', 'Cartas/Itens/16.jpg', 'carteira', '86', NULL, 1, 0, 0, 0, 'Tire os itens leves da sua mochila e coloque nessa pochete, permite levar um item pesado a mais.', TRUE, 2, 0, FALSE),
(53, 'Espada cabo pequeno', 'Item', 'Cartas/Itens/17.jpg', 'mão', '83;84', NULL, 3, 0, 0, 0, 'Não pode ser usada por personagem homem, cabo muito pequeno.', TRUE, 2, 400, FALSE),
(54, 'Barraca camuflada', 'Item', 'Cartas/Itens/18.jpg', 'carteira', '86', NULL, 2, 0, 0, 0, 'Perfeito para passar a noite, +2 de forca.', TRUE, 2, 400, FALSE),
(55, 'Colete militar', 'Item', 'Cartas/Itens/19.jpg', 'Corpo', '82', NULL, 3, 0, 0, 0, 'Contra tiros do inimigo e arranhões de zumbi, +3 de força.', TRUE, 2, 600, FALSE),
(56, 'Ajuda familia', 'Item', 'Cartas/Itens/2.jpg', 'Descartavel', NULL, NULL, 2, 0, 0, 0, '+2 de força para qualquer um dos lados.', TRUE, 5, 100, TRUE),
(58, 'Calça militar', 'Item', 'Cartas/Itens/21.jpg', 'carteira', '86', NULL, 3, 0, 0, 0, 'Segura contra arranhões nas pernas, +3 de força.', TRUE, 2, 600, FALSE),
(59, 'Uzi', 'Item', 'Cartas/Itens/22.jpg', 'mão', '83;84', NULL, 5, 0, 0, 0, 'Uma arma leve e compacta para locais apertados e com muitos zumbis, +5 de força.', TRUE, 2, 800, FALSE),
(60, 'Pepper box', 'Item', 'Cartas/Itens/23.jpg', 'mão', '83;84', NULL, 4, 0, 0, 0, 'Sim, não faz sentido, +4 de força.', TRUE, 1, 600, FALSE),
(61, 'Roupa camuflada', 'Item', 'Cartas/Itens/24.jpg', 'Corpo', '82', NULL, 4, 0, 0, 0, 'Uma camuflagem muito útil, +4 de força.', TRUE, 2, 600, FALSE),
(62, 'Capacete de moto', 'Item', 'Cartas/Itens/25.jpg', 'Cabeça', '81', NULL, 2, 0, 0, 0, 'Já protege contra arranhões, +2 de força.', TRUE, 3, 400, FALSE),
(63, 'Capacete militar', 'Item', 'Cartas/Itens/26.jpg', 'Cabeça', '81', NULL, 3, 0, 0, 0, 'Proteger contra tiros e arranhões, +3 de força.', TRUE, 2, 600, FALSE),
(64, 'Katana', 'Item', 'Cartas/Itens/27.jpg', 'mão', '83;84', NULL, 3, 0, 0, 0, 'Leve e precisa, +3 de força.', TRUE, 2, 600, FALSE),
(65, 'Colete policial', 'Item', 'Cartas/Itens/28.jpg', 'Corpo', '82', NULL, 2, 0, 0, 0, 'Preciso contra arranhões e tiros leves, +2 de força.', TRUE, 2, 400, FALSE),
(66, 'Marreta', 'Item', 'Cartas/Itens/29.jpg', 'mão', '83;84', NULL, 4, 0, 0, 0, 'Uma dessa bem dada na cabeça olha!!!, +4 de força.', TRUE, 2, 600, FALSE),
(67, 'Ajuda familia', 'Item', 'Cartas/Itens/3.jpg', 'Descartavel', NULL, NULL, 0, 0, 0, 0, 'Dobra o valor de força do seu personagem.', TRUE, 1, 300, TRUE),
(68, 'Alabarda', 'Item', 'Cartas/Itens/30.jpg', 'mão', '83;84', NULL, 4, 0, 0, 0, 'Ocupa as duas mão, mas arranca cabeças, +4 de força.', TRUE, 2, 600, FALSE),
(69, 'Drone', 'Item', 'Cartas/Itens/31.jpg', 'carteira', '86', NULL, 3, 0, 0, 0, 'Uma vantagem para o avanço, +3 de força.', TRUE, 2, 600, FALSE),
(70, 'Ariete', 'Item', 'Cartas/Itens/32.jpg', 'carteira', '86', NULL, 3, 0, 0, 0, 'Ótima ferramenta para abrir portas, +3 de força.', TRUE, 2, 400, FALSE),
(71, 'Besta', 'Item', 'Cartas/Itens/33.jpg', 'mão', '83;84', NULL, 4, 0, 0, 0, 'Sem barulhos para atrais zumbi, +4 de força.', TRUE, 2, 800, FALSE),
(73, 'Sniper', 'Item', 'Cartas/Itens/35.jpg', 'Nivel', NULL, NULL, 0, 0, 1, 0, 'Uma ajudinha de longe, suba um nível.', TRUE, 5, 0, FALSE),
(77, 'Caibro', 'Item', 'Cartas/Itens/39.jpg', 'mão', '83;84', NULL, 3, 0, 0, 0, 'Só pode ser usado por homens, muito pesado para carregar, +3 de força.', TRUE, 2, 400, FALSE),
(78, 'Ajuda familia', 'Item', 'Cartas/Itens/4.jpg', 'Descartavel', NULL, NULL, 5, 0, 0, 0, '+5 de força para qualquer um dos lados.', TRUE, 3, 300, TRUE),
(79, 'Luva espinho', 'Item', 'Cartas/Itens/40.jpg', 'mão', '83;84', NULL, 2, 0, 0, 0, 'Pense no prazer de socar com este item!!!, +2 de força.', TRUE, 3, 300, FALSE),
(80, 'Serra eletrica', 'Item', 'Cartas/Itens/41.jpg', 'mão', '83;84', NULL, 3, 0, 0, 0, 'O barulho é ruim, mas a visão de cabeças caindo é satisfatório, +3 de força.', TRUE, 2, 600, FALSE),
(81, 'Pedra grande', 'Item', 'Cartas/Itens/42.jpg', 'mão', '83;84', NULL, 3, 0, 0, 0, 'Pesado, mas se pega na cuca, +3 de força.', TRUE, 5, 0, FALSE),
(83, 'Lança', 'Item', 'Cartas/Itens/44.jpg', 'mão', '83;84', NULL, 1, 0, 0, 0, 'Simples de fazer, qualquer um tem, +1 de força.', TRUE, 4, 200, FALSE),
(84, 'Canivete', 'Item', 'Cartas/Itens/45.jpg', 'mão', '83;84', NULL, 1, 0, 0, 0, 'Cabe na carteira essa, +1 de força.', TRUE, 5, 0, FALSE),
(85, 'Tênis de corrida', 'Item', 'Cartas/Itens/46.jpg', 'Pés', '85', NULL, 2, 0, 0, 0, 'Ótimo para avançar ou fugir, +1 de fuga', TRUE, 3, 400, FALSE),
(86, 'Coturno', 'Item', 'Cartas/Itens/47.jpg', 'Pés', '85', NULL, 5, 0, 0, 0, 'Esse é raro, Armadilhas não afetam este jogador.', TRUE, 1, 700, FALSE),
(87, 'Chinelo', 'Item', 'Cartas/Itens/48.jpg', 'Pés', '85', NULL, 2, 0, 0, 0, 'Tú é pobre em? +2 de força.', TRUE, 5, 200, FALSE),
(88, 'Drop', 'Item', 'Cartas/Itens/5.jpg', 'Descartavel', NULL, NULL, 0, 0, 0, 0, 'Compre 3 cartas do descarte de item.', TRUE, 1, 0, FALSE),
(89, 'Dumpster', 'Item', 'Cartas/Itens/6.jpg', 'Descartavel', NULL, NULL, 0, 0, 0, 0, 'Procure uma carta de qualquer descarte e fique com ela.', TRUE, 1, 0, FALSE),
(90, 'Suborno', 'Item', 'Cartas/Itens/7.jpg', 'Descartavel', NULL, NULL, 0, 0, 0, 0, 'Escolha o valor do dado.', TRUE, 1, 0, FALSE),
(91, 'Boleadeira', 'Item', 'Cartas/Itens/8.jpg', 'Descartavel', NULL, NULL, 0, 0, 0, 0, 'Este jogador não consegue fugir de um combate.', TRUE, 1, 1300, FALSE),
(92, 'Um empurrãozinho', 'Item', 'Cartas/Itens/9.jpg', 'Descartavel', NULL, NULL, 0, 0, 0, 0, 'O jogador volta para o combate mesmo que ele tenha conseguido fugir e necessita de +1 de fuga.', TRUE, 2, 300, FALSE)
ON CONFLICT (id) DO UPDATE SET
  nome_carta = EXCLUDED.nome_carta,
  tipo_carta = EXCLUDED.tipo_carta,
  caminho_imagem = EXCLUDED.caminho_imagem,
  categoria = EXCLUDED.categoria,
  equipar_onde = EXCLUDED.equipar_onde,
  n_pode_equipar = EXCLUDED.n_pode_equipar,
  forca = EXCLUDED.forca,
  item = EXCLUDED.item,
  nivel = EXCLUDED.nivel,
  fulga_minima = EXCLUDED.fulga_minima,
  texto_da_carta = EXCLUDED.texto_da_carta,
  permite_mochila = EXCLUDED.permite_mochila,
  qtd_max = EXCLUDED.qtd_max,
  valor = EXCLUDED.valor,
  uso_em_combate = EXCLUDED.uso_em_combate
;
